version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.12-fpm
      - image: circleci/mysql:8.0.22-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: lemurro
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      # install lemurro
      - run: composer global require --no-progress --no-scripts --no-plugins lemurro/installer
      - run: ~/.composer/vendor/bin/lemurro new testproject --lv=2.0 --api --skip --silent
      - run: composer install --working-dir=/home/circleci/project/testproject/api/vendor/lemurro/api-core
      # prepare the database
      - run: sudo apt install default-mysql-client
      - run: mysql -u root lemurro < /home/circleci/project/testproject/api/database.sql
      - run: mysql -u root --execute="SELECT * FROM lemurro.users"
      # run server
      - run: php -S 127.0.0.1:8000 -t /home/circleci/project/testproject/api/public > /dev/null 2>&1 &
      # run tests
      - run: php /home/circleci/project/testproject/api/vendor/bin/codecept run api
      - run: php /home/circleci/project/testproject/api/vendor/lemurro/api-core/vendor/bin/codecept run api
