version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.12-fpm
      - image: circleci/mysql:8.0.22-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: lemurro
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
      - run: sudo docker-php-ext-install zip pdo_mysql
      # set variables
      - run: echo "export PROJECT_NAME=testproject" >> $BASH_ENV
      - run: echo "export PROJECT_FOLDER=/home/circleci/project/testproject" >> $BASH_ENV
      # install lemurro
      - run: composer global require --no-progress --no-scripts --no-plugins lemurro/installer
      - run: ~/.composer/vendor/bin/lemurro new ${PROJECT_NAME} --lv=2.0 --api --skip --silent
      - run: cd ${PROJECT_FOLDER}/api/vendor/lemurro/api-core
      - run: ls
      - run: composer install
      # prepare the database
      - run: mysql -e 'CREATE DATABASE IF NOT EXISTS lemurro;'
      - run: mysql -u root lemurro < ${PROJECT_FOLDER}/api/database.sql
      # run server
      - run: php -S 127.0.0.1:8000 -t ${PROJECT_FOLDER}/api/public > /dev/null 2>&1 &
      # run tests
      - run: php ${PROJECT_FOLDER}/api/vendor/bin/codecept run api
      - run: php ${PROJECT_FOLDER}/api/vendor/lemurro/api-core/vendor/bin/codecept run api
