version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.12-fpm
      - image: circleci/mysql:8.0.22-ram
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: lemurro
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
      - run: sudo docker-php-ext-install zip pdo_mysql
      # install lemurro
      - run: composer global require --no-progress --no-scripts --no-plugins lemurro/installer
      - run: ~/.composer/vendor/bin/lemurro new testproject --lv=2.0 --api --skip --silent
      - run: ls /home/circleci/project/testproject
      #- run: ls ~/testproject/api
      #- run: ls ~/testproject/api/vendor
      #- run: ls ~/testproject/api/vendor/lemurro
      #- run: ls ~/testproject/api/vendor/lemurro/api-core
      #- run: composer install --working-dir=$CIRCLE_WORKING_DIRECTORY/testproject/api/vendor/lemurro/api-core
      # prepare the database
      #- run: mysql -u root lemurro < $CIRCLE_WORKING_DIRECTORY/testproject/api/database.sql
      # run server
      #- run: php -S 127.0.0.1:8000 -t $CIRCLE_WORKING_DIRECTORY/testproject/api/public > /dev/null 2>&1 &
      # run tests
      #- run: php $CIRCLE_WORKING_DIRECTORY/testproject/api/vendor/bin/codecept run api
      #- run: php $CIRCLE_WORKING_DIRECTORY/testproject/api/vendor/lemurro/api-core/vendor/bin/codecept run api
