version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4.12-fpm-buster
      - image: circleci/mysql:8.0.22
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_USER: root
          MYSQL_DATABASE: lemurro
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_PASSWORD: ''
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz && rm dockerize-linux-amd64-v0.6.1.tar.gz
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      # install lemurro
      - run: composer global require --no-progress --no-scripts --no-plugins lemurro/installer
      - run: ~/.composer/vendor/bin/lemurro new testproject --lv=2.0 --api --skip --silent
      - run: composer install --working-dir=/home/circleci/project/testproject/api/vendor/lemurro/api-core
      # prepare database
      - run: sudo apt install default-mysql-client
      - run: mysql -h 127.0.0.1 -u root lemurro < /home/circleci/project/testproject/api/database.sql
      - run: mysql -h 127.0.0.1 -u root --execute="SELECT * FROM lemurro.users"
      # run server
      - run: sudo php -S localhost:8000 -t /home/circleci/project/testproject/api/public
      # prepare tests
      - run: cd /home/circleci/project/testproject/api/tests && cp ./api.suite.dist.yml ./api.suite.yml
      - run: cd /home/circleci/project/testproject/api/vendor/lemurro/api-core/tests && cp ./api.suite.dist.yml ./api.suite.yml
      - run: cd /home/circleci/project/testproject/api/tests && sed -i 's/http\:\/\/lemurro\-api\.localhost/localhost\:8000/g' ./api.suite.yml
      - run: cd /home/circleci/project/testproject/api/vendor/lemurro/api-core/tests && sed -i 's/http\:\/\/lemurro\-api\.localhost/localhost\:8000/g' ./api.suite.yml
      - run: cat /home/circleci/project/testproject/api/tests/api.suite.yml
      - run: cat /home/circleci/project/testproject/api/vendor/lemurro/api-core/tests/api.suite.yml
      # run tests
      - run: cd /home/circleci/project/testproject/api && php vendor/bin/codecept run api
      - run: cd /home/circleci/project/testproject/api/vendor/lemurro/api-core && php vendor/bin/codecept run api
